### ISSUE TITLE
Hardcoded usernames

### ISSUE THREAD

**Issue by macruspareto** [Postuf/telegram-osint-lib#114]
Hey guys!

In the sourcecode I can see a bunch of hardcoded usernames -
Asen_17
asensio_17
phuketrusa
a_averyanova_m
ru2chnews

and phone numbers -
79265558802
79803100357
79264598639

What was the reason for putting them there and have you obtained any permission from the original owners of these accounts?

**Comment by wkejqb** [comment]
Those are our own accounts/public chats we used for testing, no private information shared. However, to prevent confusion, we haved removed most of those references.
