### ISSUE TITLE
 Uncaught TelegramOSINT\Exception\TGException: ERR_TL_CONTAINER_BAD_AUTHKEY_ID: 

### ISSUE THREAD

**Issue by fhartavi** [Postuf/telegram-osint-lib#121]
PHP Fatal error:  Uncaught TelegramOSINT\Exception\TGException: ERR_TL_CONTAINER_BAD_AUTHKEY_ID:  in C:\Program Files\Ampps\www\telegram\vendor\postuf\telegram-api-lib\src\TGConnection\SocketMessenger\EncryptedSocketMessenger.php:189
Stack trace:
#0 C:\Program Files\Ampps\www\telegram\vendor\postuf\telegram-api-lib\src\TGConnection\SocketMessenger\EncryptedSocketMessenger.php(155): TelegramOSINT\TGConnection\SocketMessenger\EncryptedSocketMessenger->decryptPayload(false)
#1 C:\Program Files\Ampps\www\telegram\vendor\postuf\telegram-api-lib\src\TGConnection\SocketMessenger\EncryptedSocketMessenger.php(133): TelegramOSINT\TGConnection\SocketMessenger\EncryptedSocketMessenger->readMessageFromSocket()
#2 C:\Program Files\Ampps\www\telegram\vendor\postuf\telegram-api-lib\src\Registration\RegistrationFromTgApp.php(287): TelegramOSINT\TGConnection\SocketMessenger\EncryptedSocketMessenger->readMessage()
#3 C:\Program Files\Ampps\www\telegram\vendor\postuf\telegram-api-lib\src\Registration\AccountRegistrar.php(27): TelegramOSINT\Regist in C:\Program Files\Ampps\www\telegram\vendor\postuf\telegram-api-lib\src\TGConnection\SocketMessenger\EncryptedSocketMessenger.php on line 189

Fatal error: Uncaught TelegramOSINT\Exception\TGException: ERR_TL_CONTAINER_BAD_AUTHKEY_ID:  in C:\Program Files\Ampps\www\telegram\vendor\postuf\telegram-api-lib\src\TGConnection\SocketMessenger\EncryptedSocketMessenger.php:189
Stack trace:
#0 C:\Program Files\Ampps\www\telegram\vendor\postuf\telegram-api-lib\src\TGConnection\SocketMessenger\EncryptedSocketMessenger.php(155): TelegramOSINT\TGConnection\SocketMessenger\EncryptedSocketMessenger->decryptPayload(false)
#1 C:\Program Files\Ampps\www\telegram\vendor\postuf\telegram-api-lib\src\TGConnection\SocketMessenger\EncryptedSocketMessenger.php(133): TelegramOSINT\TGConnection\SocketMessenger\EncryptedSocketMessenger->readMessageFromSocket()
#2 C:\Program Files\Ampps\www\telegram\vendor\postuf\telegram-api-lib\src\Registration\RegistrationFromTgApp.php(287): TelegramOSINT\TGConnection\SocketMessenger\EncryptedSocketMessenger->readMessage()
#3 C:\Program Files\Ampps\www\telegram\vendor\postuf\telegram-api-lib\src\Registration\AccountRegistrar.php(27): TelegramOSINT\Regist in C:\Program Files\Ampps\www\telegram\vendor\postuf\telegram-api-lib\src\TGConnection\SocketMessenger\EncryptedSocketMessenger.php on line 189

**Comment by wkejqb** [comment]
Issue confirmed, investigating. For now, please use commit 809a3a24b064f0ce6004b361e5866808379ac558 for registration, it works there.

**Comment by fhartavi** [comment]
Sir i am not working with docker , i am working with composer installed with composer.

Thanks

**Comment by wkejqb** [comment]
Fixed: https://github.com/Postuf/telegram-osint-lib/pull/122
Pls update to latest release: https://packagist.org/packages/postuf/telegram-api-lib#v0.2.37
