### ISSUE TITLE
how to login/create auth key for account that is already exist?

### ISSUE THREAD

**Issue by iamDonkey** [Postuf/telegram-osint-lib#140]
i tried to login with an account that already exists but the library fails at throwing ERR_REG_USER_ALREADY_EXISTS 
can you please make it to allow login ? i guess library only allows to create auth key for fresh account?

**Comment by Qusonann** [comment]
You are right, this is currently not implemented.

**Comment by iamDonkey** [comment]
> You are right, this is currently not implemented, PRs are welcome.

i am a noob and beginner level in mtproto :(

**Comment by iamDonkey** [comment]
any update bros?

**Comment by Qusonann** [comment]
We don't plan to implement this feature in near future.

**Comment by Qusonann** [comment]
@iamDonkey https://github.com/Postuf/telegram-osint-lib/tree/feature/re-reg please try this branch.

**Comment by iamDonkey** [comment]
i am going to test it.  thanks my bro.

**Comment by iamDonkey** [comment]
@Qusonann @Ririconj hey my bros, 
can you please add  2step password support also? https://core.telegram.org/api/srp
the re-registration.php crashes with exception SESSION_PASSWORD_NEEDED

**Comment by Qusonann** [comment]
Hi!
> This is currently not implemented, PRs are welcome.

**Comment by iamDonkey** [comment]
@Qusonann
i do not have enough knowledge to make it myself. can you please consider this to implement as next feature ?

**Comment by iamDonkey** [comment]
@Qusonann hi bro, any update on this?

**Comment by Qusonann** [comment]
Currently no updates, we are busy doing other things.

**Comment by iamDonkey** [comment]
ok bro.  i am eagerly waiting 🙄

**Comment by Ririconj** [comment]
Btw, we dont mind help
