### ISSUE TITLE
Fatal error: Declaration of TelegramOSINT

### ISSUE THREAD

**Issue by Zhenyoker** [Postuf/telegram-osint-lib#151]
Hello! what am I doing wrong?

`Fatal error: Declaration of TelegramOSINT\Registration\RegistrationFromTgApp::onMessage(TelegramOSINT\MTSerialization\AnonymousMessage $message) must be compatible with TelegramOSINT\TGConnection\SocketMessenger\MessageListener::onMessage(TelegramOSINT\MTSerialization\AnonymousMessage $message): void in /app/src/Registration/RegistrationFromTgApp.php on line 285
`

**Comment by Qusonann** [comment]
Please update to latest master and try again.
