### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by GamiDPC** [Postuf/telegram-osint-lib#167]
Ошибка при установке
![image](https://user-images.githubusercontent.com/17031085/86285700-c4b41180-bbed-11ea-86e0-fe3e2bd4a5bc.png)

**Comment by Qusonann** [comment]
Там пишут что нужно установить расширение GMP. Возможно, оно уже есть в комплекте и нужно его включить в `php.ini`, там будет что-то вроде `;extension=php_gmp.dll`, это надо раскомментировать.
Но вообще под windows библиотеку никто не тестировал, рекомендую воспользоваться docker окружением или отдельной инсталляцией linux.
