### ISSUE TITLE
[question] any tutorial for making own scenario?

### ISSUE THREAD

**Issue by iamDonkey** [Postuf/telegram-osint-lib#179]
for example
if i want to use this library to get  response of this mtproto method [messages.getStickerSet ](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/tl/api.tl#L1305) how to do that?

**Comment by Qusonann** [comment]
Hi!
No problem to do that, we are going to update documentation to reflect this.
Currently we are working an example, it would cover basic steps of implementing scenario:
1. implementing required nodes
2. adding calls to client
3. implementing the scenario itself.

**Comment by iamDonkey** [comment]
Thanks my bro. I am waiting.

**Comment by Qusonann** [comment]
You can check actual implementation here: https://github.com/Postuf/telegram-osint-lib/pull/180
Most things done are self-documenting, detailed docs to be added later.
