### ISSUE TITLE
Uncaught TelegramOSINT\Exception\TGException: ERR_REG_USER_ALREADY_EXISTS

### ISSUE THREAD

**Issue by DKanarsky** [Postuf/telegram-osint-lib#195]
Fatal error: Uncaught TelegramOSINT\Exception\TGException: ERR_REG_USER_ALREADY_EXISTS: TelegramOSINT\MTSerialization\OwnImplementation\OwnAnonymousMessage Object
(
    [object:TelegramOSINT\MTSerialization\OwnImplementation\OwnAnonymousMessage:private] => Array
        (
            [_] => auth.sentCode
            [flags] => 2
            [type] => Array
                (
                    [_] => auth.sentCodeTypeApp
                    [length] => 5
                )

            [phone_code_hash] => 258747dd89b4c93658
            [next_type] => Array
                (
                    [_] => auth.codeTypeSms
                )

            [timeout] =>
        )

    [type:TelegramOSINT\MTSerialization\OwnImplementation\OwnAnonymousMessage:private] => auth.sentCode
)
 in /app/src/Registration/RegistrationFromTgApp.php:120
Stack trace:
#0 /app/src/TGConnection/SocketMessenger/EncryptedSocketCallbacks/CallbackMessageListener.php(22): TelegramOSINT\Registration\RegistrationFromTgApp->TelegramOSINT\Registration\{clos in /app/src/Registration/RegistrationFromTgApp.php on line 120

I have already logged in mobile telegram client with this phone number. Does it mean I can't use the number in lib?

**Comment by Qusonann** [comment]
Currently this script supports only newly-registered numbers. Please try `re-registration.php`.
