### ISSUE TITLE
Need help with registration

### ISSUE THREAD

**Issue by Thoufak** [Postuf/telegram-osint-lib#200]
Hi! Thank you very much for the library. I tried running the registration script with a phone number that had not been registered in Telegram, but with no success.

This is what I did:
1. `php examples/registration.php`
2. Entered the phone
3. Entered the received code

This is the last piece of the output I saw:
![Screenshot 2020-08-29 at 17 23 51](https://user-images.githubusercontent.com/40132582/91640168-31982c00-ea24-11ea-843e-31d5acf4a18d.png)

I then tried adding this phone number to my Telegram contacts. It wasn't found, which means the registration process wasn't finished.
After that I also tried logging in with the same phone using the official app. I wanted to see if maybe the phone got banned after the signup attempt. However, the app didn't say that the phone was banned.

Please see the full logs attached too.
[postuf-osint-registration-logs.txt](https://github.com/Postuf/telegram-osint-lib/files/5145456/postuf-osint-registration-logs.txt)

**Comment by tombouctou** [comment]
Please try the same number again, you should have AuthKey: ... message at the end, that means registration is successful.

**Comment by Thoufak** [comment]
Thank you. I tried a different number and it worked.
