### ISSUE TITLE
No AuthKey

### ISSUE THREAD

**Issue by truemoroz** [Postuf/telegram-osint-lib#209]
I see only this while registration

`SMS code: 12592

05.11.2020 12:27:50 | Write_Message_Binary: 8115d5bc0b373931363030353637353912306566656562386235643162343963306632000531323539320000

05.11.2020 12:27:50 | Write_Message_ID: 6891553640960966000

05.11.2020 12:27:50 | Write_Message_TL: Array

(
    [_] => auth.signIn
    [phone_number] => 79160056759
    [phone_code_hash] => 0efeeb8b5d1b49c0f2
    [phone_code] => 12592
)
`

**Comment by Ririconj** [comment]
Hello, registration goes in 2 steps: signIn and signUp next with a little idle. Do you see signUp afterwards?

**Comment by Ririconj** [comment]
Problem found. Going to be fixed here - #210 
P.S Bug was introduced by silly contributor :)
