### ISSUE TITLE
auth.codeType

### ISSUE THREAD

**Issue by vrtme** [Postuf/telegram-osint-lib#227]
auth.codeTypeCall и auth.codeTypeFlashCall планируется? почему то автоматически не всем дает подобные флаги
![image](https://user-images.githubusercontent.com/65429583/135944423-36040228-3c6b-496c-bb7f-693ebaaafa9d.png)

**Comment by vrtme** [comment]
передать бы флаг allow_flashcall & current_number

**Comment by Ririconj** [comment]
Call и FlashCall пока не планируется к реализации

**Comment by vrtme** [comment]
> Call и FlashCall пока не планируется к реализации

ну я так понимаю TL схему дописать и ввести функционал самому проще)

**Comment by Ririconj** [comment]
Будем рады любой помощи в расширении функционала)

**Comment by vrtme** [comment]
на работу возьмете?)

**Comment by Ririconj** [comment]
Берем только по результатам тестирования - https://team.postuf.com/questionnaire. Но помочь в доработке можно и без трудоустройства к нам - в рамках OpenSource Community.
