### ISSUE TITLE
Uncaught TelegramOSINT\Exception\TGException: ERR_CANT_CONNECT

### ISSUE THREAD

**Issue by DKanarsky** [Postuf/telegram-osint-lib#97]
I use your docker container with my proxy settings,  and I can curl telegram API inside container. But when I'm trying  to register using `php examples/registration.php` an error appears:

`Fatal error: Uncaught TelegramOSINT\Exception\TGException: ERR_CANT_CONNECT:  in /app/src/TGConnection/Socket/TcpSocket.php:37
Stack trace:
#0 /app/src/Auth/Protocol/BaseAuthorization.php(85): TelegramOSINT\TGConnection\Socket\TcpSocket->__construct(Object(TelegramOSINT\TGConnection\DataCentre))
#1 /app/src/Auth/Protocol/AppAuthorization.php(20): TelegramOSINT\Auth\Protocol\BaseAuthorization->__construct(Object(TelegramOSINT\TGConnection\DataCentre))
#2 /app/src/Registration/RegistrationFromTgApp.php(171): TelegramOSINT\Auth\Protocol\AppAuthorization->__construct(Object(TelegramOSINT\TGConnection\DataCentre))
#3 /app/src/Registration/RegistrationFromTgApp.php(119): TelegramOSINT\Registration\RegistrationFromTgApp->requestBlankAuthKey(Object(Closure))
#4 /app/src/Registration/AccountRegistrar.php(39): TelegramOSINT\Registration\RegistrationFromTgApp->requestCodeForPhone('******', Object(Closure))
#5 /app/examples/registration.php(24): TelegramOSINT\Registration\AccountRegistrar->requestCodeForPhone('********', Obje in /app/src/TGConnection/Socket/TcpSocket.php on line 37
root@ac21a5713014:/app# php examples/registration.php`

**Comment by wkejqb** [comment]
Did you use socks5 proxy?
Only socks5 is currently supported.

**Comment by anton-postuf** [comment]
> 
> 
> Did you use socks5 proxy?
> Only socks5 is currently supported. We use https://github.com/Postuf/SocksProxyAsync for proxy connections.

"Currently" means TG does not use HTTP at all for now: neither during registration nor authorization

**Comment by DKanarsky** [comment]
I ran docker container with HTTP_PROXY and HTTPS_PROXY settings. I think that was my mistake. Can you explain how to setup proxy settings in this project? I want to use my host tor socks5 proxy.

**Comment by wkejqb** [comment]
Sure, that wouldn't work ) We don't use those env vars.
Proxy format we use: https://github.com/Postuf/SocksProxyAsync/blob/master/src/Proxy.php#L26
To use proxy, save it to `reg_proxy.txt` and uncomment this line: https://github.com/Postuf/telegram-osint-lib/blob/master/examples/registration.php#L12
